Repository TravisWheelerLab/polyA, pull requests merged in 2021-06, with the labels that each got.

#71 Complexity adjusted scoring
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  converters/alignment_to_stockholm.sh
  converters/cm_to_stockholm.py
  converters/rm_to_stockholm.py
  docs/.gitignore
  docs/Makefile
  docs/make.bat
  docs/source/conf.py
  docs/source/index.rst
  docs/source/modules.rst
  docs/source/polyA.rst
  fixtures/ultra_test_files/ex13.fa.cm.matrix
  fixtures/ultra_test_files/ex13.fa.cm.sto
  fixtures/ultra_test_files/ex25.fa.cm.matrix
  fixtures/ultra_test_files/ex25.fa.cm.sto
  fixtures/ultra_test_files/ex26.fa.cm.matrix
  fixtures/ultra_test_files/ex26.fa.cm.sto
  fixtures/ultra_test_files/ex27.fa.cm.matrix
  fixtures/ultra_test_files/ex27.fa.cm.sto
  fixtures/ultra_test_files/ex29.fa.cm.matrix
  fixtures/ultra_test_files/ex29.fa.cm.sto
  fixtures/ultra_test_files/ex30.fa.cm.matrix
  fixtures/ultra_test_files/ex30.fa.cm.sto
  polyA/_app.py
  polyA/_options.py
  polyA/_runners.py
  polyA/calculate_score.py
  polyA/constants.py
  polyA/converters/__init__.py
  polyA/fill_align_matrix.py
  polyA/fill_node_confidence.py
  polyA/fill_probability_matrix.py
  polyA/load_alignments.py
  polyA/substitution_matrix.py
  tests/RunUltraTests.sh
  tests/test_fill_align_matrix.py
Labels: enhancement

#69 Improve debugging output
  benchmarks/README.md
  benchmarks/entrypoint.py
  benchmarks/run_benchmark.sh
  polyA/_app.py
  polyA/_options.py
  polyA/_runners.py
  polyA/fill_node_confidence.py
  polyA/output.py
  polyA/performance.py
  polyA/printers.py
Labels: interface, performance, testing

#74 Update requirements.txt on docs build
  Makefile
Labels: documentation
